// Copyright 2026 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.
import { access, mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { CLIDisplay } from "@3sixty/cli-core";
import { GeneralError, I18n, Is, ObjectHelper, StringHelper } from "@3sixty/core";
import type { IJsonSchema } from "@3sixty/tools-models";
import Ajv2020, { type KeywordCxt } from "ajv/dist/2020.js";
import { type Code, Name, strConcat } from "ajv/dist/compile/codegen/index.js";
import type { SchemaEnv } from "ajv/dist/compile/index.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import { callRef } from "ajv/dist/vocabularies/core/ref.js";
import formatsPlugin from "ajv-formats";
import type { IExternalValidator } from "../models/IExternalValidator.js";
import type { ITsToSchemaConfig } from "../models/ITsToSchemaConfig.js";

/**
 * The prefix added to a schema title to name its compiled validator, so a package can export
 * the validators from its barrel without colliding with its other exports.
 */
export const COMPILED_VALIDATOR_PREFIX = "Compiled";

/**
 * The keyword which replaces refs to validators imported from dependencies.
 */
const EXTERNAL_REF_KEYWORD = "externalRef";

/**
 * The keyword which replaces an anyOf of const values defined by an "as const" object.
 */
const CONST_LIST_KEYWORD = "constList";

/**
 * The name of the generated module.
 */
const MODULE_NAME = "validators";

/**
 * The pattern for base64 content, matching the contentEncoding validation of data-core.
 */
const BASE64_REGEX = /^(?=(?:.{4})+$)[A-Za-z0-9+/]*={0,2}$/;

/**
 * The formats exported by data-core, so the generated module does not depend on AJV.
 */
const FORMATS_EXPORT = "JsonSchemaFormats";

/**
 * The header for the generated module. The generated code is not type safe, so type checking is
 * disabled for it, while the exports are typed so the declarations are generated from them. The
 * packages exclude the generated module from their lint configuration.
 */
const HEADER = [
	"// Copyright 2026 IOTA Stiftung.",
	"// SPDX-License-Identifier: Apache-2.0.",
	"// This file is generated by ts-to-schema, do not edit it directly.",
	"// @ts-nocheck",
	// The code embeds the schema descriptions, which are not spell checked in the schemas.
	"/* cspell:disable */"
].join("\n");

/**
 * Compile the generated schemas into a module exporting a validator per schema, named by the
 * schema title with the compiled prefix, as TypeScript so the package compiles it. Refs in the namespaces of
 * the external references use the compiled validator exported by the dependency of the package
 * which ships the schema, otherwise the external schema is compiled into the module.
 * @param config The configuration for the app.
 * @param schemas The generated schemas to compile.
 * @param compiledFolder The folder to write the compiled module to.
 * @param packageFolder The folder of the package, used to find its dependencies.
 */
export async function compileValidators(
	config: ITsToSchemaConfig,
	schemas: IJsonSchema[],
	compiledFolder: string,
	packageFolder: string
): Promise<void> {
	CLIDisplay.break();
	CLIDisplay.task(I18n.formatMessage("commands.ts-to-schema.progress.compilingValidators"));

	const externalNamespaces = Object.values(config.externalReferences ?? {}).map(url =>
		url.slice(0, url.lastIndexOf("/") + 1)
	);
	const { externalSchemas, externalValidators } = await readExternalSchemas(
		packageFolder,
		externalNamespaces
	);

	const importedValidators = new Map<string, IExternalValidator>();
	const constLists = await findConstLists(config, schemas, compiledFolder);

	const ajv = createCompiler(async (uri: string): Promise<IJsonSchema> => {
		if (!externalNamespaces.some(ns => uri.startsWith(ns))) {
			throw new GeneralError("commands", "commands.ts-to-schema.schemaNotExternal", { uri });
		}
		CLIDisplay.value(I18n.formatMessage("commands.ts-to-schema.progress.fetchingSchema"), uri, 1);
		const response = await fetch(uri);
		if (!response.ok) {
			throw new GeneralError("commands", "commands.ts-to-schema.schemaFetchFailed", {
				uri,
				status: response.status
			});
		}
		return replaceExternalRefs((await response.json()) as IJsonSchema, externalValidators);
	});

	// Call an imported validator the same way AJV calls the validator of a $ref, so its errors
	// and evaluated properties are merged into the calling validator.
	ajv.addKeyword({
		keyword: EXTERNAL_REF_KEYWORD,
		schemaType: "string",
		/**
		 * Generate the code which calls the imported validator.
		 * @param cxt The keyword context.
		 */
		code(cxt: KeywordCxt): void {
			const external = externalValidators[cxt.schema as string];
			importedValidators.set(external.exportName, external);
			const validate = cxt.gen.scopeValue("keyword", {
				ref: external.validator,
				code: Ajv2020._`importModule(${external.moduleSpecifier})[${external.exportName}]`
			});
			// Only the evaluated properties of the validator are read from the schema environment.
			callRef(cxt, validate, { validate: external.validator } as unknown as SchemaEnv, false);
		}
	});

	// Validate a list of const values against the "as const" object which defines them, rather than
	// generating the code for every value. The errors are the same as those of the anyOf it replaces.
	ajv.addKeyword({
		keyword: CONST_LIST_KEYWORD,
		schemaType: "string",
		/**
		 * Generate the code which validates the data against the values of the object.
		 * @param cxt The keyword context.
		 */
		code(cxt: KeywordCxt): void {
			const constList = constLists[cxt.schema as string];
			const { gen, data, it } = cxt;
			// The names AJV uses for these variables in every generated validator.
			const n = {
				vErrors: new Name("vErrors"),
				errors: new Name("errors"),
				instancePath: new Name("instancePath")
			};
			const values = gen.scopeValue("keyword", {
				ref: constList.values,
				code: Ajv2020._`Object.values(importModule(${constList.moduleSpecifier})[${constList.exportName}])`
			});
			const instancePath = strConcat(n.instancePath, it.errorPath);
			const anyOfPath = `${it.errSchemaPath}/anyOf`;
			// Uses the error helpers which compactErrors adds to the module.
			const pushError = (error: Code): void => {
				gen.assign(n.vErrors, Ajv2020._`pushError(${n.vErrors}, ${error})`);
				gen.code(Ajv2020._`${n.errors}++`);
			};
			gen.if(Ajv2020._`!${values}.includes(${data})`, () => {
				const i = gen.name("i");
				gen.for(Ajv2020._`let ${i} = 0; ${i} < ${values}.length; ${i}++`, () =>
					pushError(
						Ajv2020._`createError(${instancePath}, ${anyOfPath} + "/" + ${i} + "/const", "const", { allowedValue: ${values}[${i}] }, "must be equal to constant")`
					)
				);
				pushError(
					Ajv2020._`createError(${instancePath}, ${anyOfPath}, "anyOf", {}, "must match a schema in anyOf")`
				);
			});
		}
	});

	for (const schema of externalSchemas) {
		ajv.addSchema(replaceExternalRefs(schema, externalValidators));
	}

	const compileSchemas = schemas.map(s =>
		replaceExternalRefs(replaceConstList(s, constLists), externalValidators)
	);
	for (const schema of compileSchemas) {
		ajv.addSchema(schema);
	}

	const exports: { [name: string]: string } = {};
	for (const schema of compileSchemas) {
		await ajv.compileAsync(schema);
		exports[`${COMPILED_VALIDATOR_PREFIX}${schema.title}`] = schema.$id as string;
	}

	const code = typeExports(
		convertRequires(
			removeUnusedSchemas(computeMessageKeys(compactErrors(standaloneCode.default(ajv, exports))))
		)
	);

	for (const external of importedValidators.values()) {
		CLIDisplay.value(
			I18n.formatMessage("commands.ts-to-schema.progress.importingValidator"),
			`${external.exportName} from ${external.moduleSpecifier}`,
			1
		);
	}

	await mkdir(compiledFolder, { recursive: true });
	const codeFile = path.join(compiledFolder, `${MODULE_NAME}.ts`);
	CLIDisplay.value(
		I18n.formatMessage("commands.ts-to-schema.progress.writingValidators"),
		codeFile,
		1
	);
	const dataCoreImport = new RegExp(`\\b${FORMATS_EXPORT}\\b`).test(code)
		? `import { type ICompiledValidator, ${FORMATS_EXPORT} } from "@3sixty/data-core";`
		: 'import type { ICompiledValidator } from "@3sixty/data-core";';
	await writeFile(codeFile, `${HEADER}\n${dataCoreImport}\n${code}\n`);
}

/**
 * Create the compiler for the standalone validators, with the same options, formats and
 * keywords as the validators data-core creates at runtime so they give the same results.
 * @param loadSchema The method to load a schema which is not added to the compiler.
 * @returns The compiler.
 */
function createCompiler(loadSchema: (uri: string) => Promise<IJsonSchema>): Ajv2020.Ajv2020 {
	const ajv = new Ajv2020.Ajv2020({
		allowUnionTypes: true,
		allErrors: true,
		// Disable strict tuples as it causes issues with the schema validation when
		// you have an array with fixed elements e.g. myType: [string, ...string[]]
		// https://github.com/ajv-validator/ajv/issues/1417
		strictTuples: false,
		// Compile each referenced schema to a single shared function instead of inlining its code at
		// every reference, which keeps the size of the generated module proportional to the schemas.
		inlineRefs: false,
		loadSchema,
		code: {
			source: true,
			esm: true,
			// Keep each generated declaration on its own line so unused ones can be removed.
			lines: true,
			formats: Ajv2020._`${new Name(FORMATS_EXPORT)}`
		}
	});

	// There is an inconsistency in the types of the formats plugin,
	// so we have to cast it to unknown and then to the correct type
	const applyFormats = formatsPlugin.default as unknown as (ajvInstance: unknown) => void;
	applyFormats(ajv);

	// contentEncoding is an annotation-only keyword in AJV, so replace it with one which
	// validates base64 content, generated as code so standalone validators include it.
	ajv.removeKeyword("contentEncoding");
	ajv.addKeyword({
		keyword: "contentEncoding",
		type: "string",
		schemaType: "string",
		/**
		 * Generate the code which validates the data against the content encoding.
		 * @param cxt The keyword context.
		 */
		code(cxt: KeywordCxt): void {
			// Not currently support quoted-printable, base16, base32
			if (cxt.schema === "base64") {
				const pattern = cxt.gen.scopeValue("pattern", {
					key: BASE64_REGEX.source,
					ref: BASE64_REGEX,
					code: Ajv2020._`new RegExp(${BASE64_REGEX.source})`
				});
				cxt.fail(Ajv2020._`!${pattern}.test(${cxt.data})`);
			}
		}
	});

	return ajv;
}

/**
 * Does the file or directory exist.
 * @param fileOrDirPath The path to check.
 * @returns True if it exists.
 */
async function exists(fileOrDirPath: string): Promise<boolean> {
	try {
		await access(fileOrDirPath);
		return true;
	} catch {
		return false;
	}
}

/**
 * Read a JSON file.
 * @param filePath The file to read.
 * @returns The parsed JSON.
 */
async function readJson<T>(filePath: string): Promise<T> {
	return JSON.parse(await readFile(filePath, "utf8")) as T;
}

/**
 * Read the schemas in the external namespaces shipped by the TWIN dependencies of the package,
 * using the compiled validator the dependency exports for a schema when it has one.
 * @param packageFolder The folder of the package.
 * @param externalNamespaces The external namespaces.
 * @returns The external schemas to compile and the external validators to import.
 */
async function readExternalSchemas(
	packageFolder: string,
	externalNamespaces: string[]
): Promise<{
	externalSchemas: IJsonSchema[];
	externalValidators: { [id: string]: IExternalValidator };
}> {
	const externalSchemas: IJsonSchema[] = [];
	const externalValidators: { [id: string]: IExternalValidator } = {};

	const packageJsonFile = path.join(packageFolder, "package.json");
	if (externalNamespaces.length === 0 || !(await exists(packageJsonFile))) {
		return { externalSchemas, externalValidators };
	}

	const packageJson = await readJson<{
		dependencies?: { [name: string]: string };
		devDependencies?: { [name: string]: string };
	}>(packageJsonFile);
	const dependencies = Object.keys({
		...packageJson.dependencies,
		...packageJson.devDependencies
	}).filter(d => d.startsWith("@3sixty/"));

	for (const dependency of dependencies) {
		const dependencyFolder = path.join(packageFolder, "node_modules", dependency);
		const schemasFolder = path.join(dependencyFolder, "dist", "es", "schemas");
		if (await exists(schemasFolder)) {
			const schemaFiles = (await readdir(schemasFolder)).filter(f => f.endsWith(".json"));
			const dependencySchemas = (
				await Promise.all(
					schemaFiles.map(async f => readJson<IJsonSchema>(path.join(schemasFolder, f)))
				)
			).filter(s => Is.stringValue(s.$id) && externalNamespaces.some(ns => s.$id?.startsWith(ns)));

			const packageExports =
				dependencySchemas.length > 0 ? await loadPackageExports(dependencyFolder) : undefined;

			for (const schema of dependencySchemas) {
				const exportName = `${COMPILED_VALIDATOR_PREFIX}${schema.title}`;
				const validator = packageExports?.[exportName];
				if (Is.function(validator)) {
					externalValidators[schema.$id as string] = {
						moduleSpecifier: dependency,
						exportName,
						validator: validator as IExternalValidator["validator"]
					};
				} else {
					externalSchemas.push(schema);
				}
			}
		}
	}
	return { externalSchemas, externalValidators };
}

/**
 * Load the main entry of a dependency, which exports its compiled validators if it has any.
 * @param dependencyFolder The folder of the dependency.
 * @returns The exports of the dependency, or undefined if it has no main entry.
 */
async function loadPackageExports(
	dependencyFolder: string
): Promise<{ [name: string]: unknown } | undefined> {
	const packageJson = await readJson<{
		main?: string;
		exports?: { [subpath: string]: string | { import?: string; default?: string } };
	}>(path.join(dependencyFolder, "package.json"));
	const mainExport = packageJson.exports?.["."];
	const mainPath = Is.string(mainExport)
		? mainExport
		: (mainExport?.import ?? mainExport?.default ?? packageJson.main);
	if (Is.stringValue(mainPath) && (await exists(path.join(dependencyFolder, mainPath)))) {
		return import(pathToFileURL(path.resolve(dependencyFolder, mainPath)).href);
	}
}

/**
 * Find the generated schemas which are an anyOf of const values defined by an "as const" object in
 * their source file, so the object can be used to validate them.
 * @param config The configuration for the app.
 * @param schemas The generated schemas, in the order of the types in the configuration.
 * @param compiledFolder The folder the compiled module is written to.
 * @returns The objects which define the const values, keyed by schema title.
 */
async function findConstLists(
	config: ITsToSchemaConfig,
	schemas: IJsonSchema[],
	compiledFolder: string
): Promise<{
	[title: string]: { moduleSpecifier: string; exportName: string; values: unknown[] };
}> {
	const constLists: {
		[title: string]: { moduleSpecifier: string; exportName: string; values: unknown[] };
	} = {};

	for (let i = 0; i < schemas.length; i++) {
		const schema = schemas[i];
		const typeSource = config.types[i];
		const branches = schema.anyOf;
		const isConstList =
			Is.arrayValue(branches) &&
			branches.every(
				b =>
					Is.object<IJsonSchema>(b) &&
					Object.keys(b).every(k => k === "const" || k === "description") &&
					(Is.string(b.const) || Is.number(b.const))
			);

		if (isConstList && Is.stringValue(schema.title) && Is.stringValue(typeSource)) {
			const exportName = StringHelper.pascalCase(
				path.basename(typeSource).replace(/(\.d)?\.ts$/, ""),
				false
			);
			const sourceFile = path.resolve(typeSource);
			const source = await readFile(sourceFile, "utf8");
			const values = branches.map(b => b.const);
			if (exportName === schema.title && objectValuesMatch(source, exportName, values)) {
				const relativePath = path
					.relative(compiledFolder, sourceFile)
					.replace(/\\/g, "/")
					.replace(/\.ts$/, ".js");
				constLists[schema.title] = {
					moduleSpecifier: relativePath.startsWith(".") ? relativePath : `./${relativePath}`,
					exportName,
					values
				};
			}
		}
	}

	return constLists;
}

/**
 * Is the key an array index, which Object.values lists before the other keys in numeric order.
 * @param key The key to check.
 * @returns True if the key is an array index.
 */
function isIndex(key: string): boolean {
	return /^(?:0|[1-9]\d*)$/.test(key) && Number(key) < 4294967295;
}

/**
 * Does Object.values of the "as const" object in the source give exactly the const values of the
 * schema in the same order, so the errors for each value match those of the anyOf. Integer like
 * keys are listed first by Object.values, which can reorder the values.
 * @param source The source of the file which defines the object.
 * @param exportName The name of the object.
 * @param values The const values of the schema.
 * @returns True if the values match.
 */
function objectValuesMatch(source: string, exportName: string, values: unknown[]): boolean {
	const start = source.indexOf(`export const ${exportName} = {`);
	const end = start === -1 ? -1 : source.indexOf("} as const;", start);
	if (end === -1) {
		return false;
	}

	const entries = [
		...source
			.slice(start, end)
			.matchAll(/^\s*("[^"]*"|[\w$]+)\s*:\s*("(?:[^"\\]|\\.)*"|-?\d+(?:\.\d+)?)\s*,?\s*$/gm)
	].map(m => ({ key: m[1].replace(/^"|"$/g, ""), value: JSON.parse(m[2]) as unknown }));

	const ordered = [
		...entries.filter(e => isIndex(e.key)).sort((a, b) => Number(a.key) - Number(b.key)),
		...entries.filter(e => !isIndex(e.key))
	];

	return ordered.length === values.length && ordered.every((e, i) => e.value === values[i]);
}

/**
 * Replace the anyOf of a schema whose const values are defined by an "as const" object with the
 * const list keyword.
 * @param schema The schema to replace the anyOf in.
 * @param constLists The objects which define the const values, keyed by schema title.
 * @returns The schema with the anyOf replaced.
 */
function replaceConstList(
	schema: IJsonSchema,
	constLists: { [title: string]: unknown }
): IJsonSchema {
	if (!Is.stringValue(schema.title) || !Is.object(constLists[schema.title])) {
		return schema;
	}
	return {
		...ObjectHelper.omit(schema, ["anyOf"]),
		[CONST_LIST_KEYWORD]: schema.title
	};
}

/**
 * Replace the refs to imported validators with the external ref keyword.
 * @param schema The schema to replace the refs in.
 * @param externalValidators The validators the code imports, keyed by schema $id.
 * @returns The schema with the refs replaced.
 */
function replaceExternalRefs<T>(
	schema: T,
	externalValidators: { [id: string]: IExternalValidator }
): T {
	if (Is.array(schema)) {
		return schema.map(s => replaceExternalRefs(s, externalValidators)) as T;
	}
	if (Is.object(schema)) {
		return Object.fromEntries(
			Object.entries(schema).map(([key, value]) => {
				const isExternalRef =
					key === "$ref" && Is.stringValue(value) && Is.object(externalValidators[value]);
				return isExternalRef
					? [EXTERNAL_REF_KEYWORD, value]
					: [key, replaceExternalRefs(value, externalValidators)];
			})
		) as T;
	}
	return schema;
}

/**
 * AJV emits require calls for runtime helpers even in ESM mode, and the external
 * ref keyword emits importModule calls for the imported validators, so convert them both to
 * imports. CommonJS subpaths need the extension adding for Node.js.
 * @param code The generated code.
 * @returns The code using ESM imports.
 */
function convertRequires(code: string): string {
	const imports = new Map<string, { name: string; isNamespace: boolean }>();
	const converted = code.replace(
		/(require|importModule)\("([^"]+)"\)/g,
		(match: string, importType: string, specifier: string) => {
			const isRequire = importType === "require";
			const resolved =
				isRequire && specifier.includes("/dist/") && !specifier.endsWith(".js")
					? `${specifier}.js`
					: specifier;
			if (!imports.has(resolved)) {
				imports.set(resolved, {
					name: `${isRequire ? "runtime" : "external"}${imports.size}`,
					isNamespace: !isRequire
				});
			}
			return imports.get(resolved)?.name ?? match;
		}
	);
	const importLines = [...imports].map(([specifier, { name, isNamespace }]) => {
		const binding = isNamespace ? `* as ${name}` : name;
		return `import ${binding} from "${specifier}";`;
	});
	// ES modules are always strict, so the directive is redundant.
	return `${importLines.join("\n")}\n${converted.replace(/^"use strict";\n/, "")}`;
}

/**
 * Replace the error objects and the code which adds them to the errors, which AJV repeats for every
 * error, with calls to helpers defined once in the module, and the literal messages with an index
 * into a table of the messages. The errors created are the same objects.
 * @param code The generated code.
 * @returns The code using the helpers.
 */
function compactErrors(code: string): string {
	const messages: string[] = [];
	const compacted = code
		.replace(
			/^const (err\d+) = \{instancePath(?::(.+?))?,schemaPath:("(?:[^"\\\n]|\\.)*"),keyword:("[^"\n]*"),params:(\{[^\n]*\}),message:([^\n]*)\};$/gm,
			(
				line: string,
				name: string,
				instancePath: string | undefined,
				schemaPath: string,
				keyword: string,
				params: string,
				message: string
			) => {
				let messageArg = message;
				if (/^"(?:[^"\\]|\\.)*"$/.test(message)) {
					const text = JSON.parse(message) as string;
					let index = messages.indexOf(text);
					if (index === -1) {
						index = messages.length;
						messages.push(text);
					}
					messageArg = `${index}`;
				}
				return `const ${name} = createError(${instancePath ?? "instancePath"},${schemaPath},${keyword},${params},${messageArg});`;
			}
		)
		.replace(
			/if\(vErrors === null\)\{\nvErrors = \[(err\d+)\];\n\}\nelse \{\nvErrors\.push\(\1\);\n\}\n/g,
			"vErrors = pushError(vErrors, $1);\n"
		);

	const helpers = [
		`const MESSAGES = ${JSON.stringify(messages)};`,
		"function createError(instancePath, schemaPath, keyword, params, message) {",
		'return { instancePath, schemaPath, keyword, params, ["message"]: typeof message === "number" ? MESSAGES[message] : message };',
		"}",
		"function pushError(errors, error) {",
		"if (errors === null) {",
		"return [error];",
		"}",
		"errors.push(error);",
		"return errors;",
		"}"
	].join("\n");

	// Keep the strict directive first, it is removed when the requires are converted.
	const strict = '"use strict";\n';
	return compacted.startsWith(strict)
		? `${strict}${helpers}\n${compacted.slice(strict.length)}`
		: `${helpers}\n${compacted}`;
}

/**
 * Write the message key of the AJV errors as a computed key, which is the same object, so the
 * validation messages are not mistaken for locale keys when validating the locales of a package.
 * @param code The generated code.
 * @returns The code with computed message keys.
 */
function computeMessageKeys(code: string): string {
	return code.replace(/([,{])message:/g, '$1["message"]:');
}

/**
 * Type the exported validators, so the declarations for the module are generated from them.
 * @param code The generated code.
 * @returns The code with typed exports.
 */
function typeExports(code: string): string {
	return code.replace(
		new RegExp(`^export const ${COMPILED_VALIDATOR_PREFIX}(\\w+) = `, "gm"),
		(declaration: string, title: string) =>
			`/**\n * Compiled validator for the ${title} schema.\n */\nexport const ${COMPILED_VALIDATOR_PREFIX}${title}: ICompiledValidator = `
	);
}

/**
 * AJV emits every compiled schema as a constant, even when the validation code never
 * references it, so remove the declarations which are not used anywhere else.
 * @param code The generated code.
 * @returns The code without the unused schema constants.
 */
function removeUnusedSchemas(code: string): string {
	return code.replace(/^const (schema\d+) = .*;\n/gm, (declaration: string, name: string) => {
		const isUsed = (code.match(new RegExp(`\\b${name}\\b`, "g"))?.length ?? 0) > 1;
		return isUsed ? declaration : "";
	});
}
